---
 - name: download the logstash 6.3.2 rpm from the official website
   yum:
     name: https://artifacts.elastic.co/downloads/logstash/logstash-6.3.2.rpm
     state: present
# - name: change the bind 
#   replace:
#     path: 
#     regexp:
#     replace:
#   notify:
#   - start
 - name: copy logstash.conf file to conf folder
   template:
     src: logstash.conf.j2
     dest: /etc/logstash/conf.d/logstash.conf
   notify:
   - start