---
# tasks file for dockercentos
- name: Install docker package in centos7
  yum :
    name: docker
    upda_cache: yes
    enabled: yes
    state: present
- name: import login
  include_tasks: login.yml
