---
# tasks file for mariadb103ubuntu
- name: check mysql already installed or not
  command: mysql --version
  ignore_errors: true
  register: mysql_exist
- name: remove existing mysql
  package:
    name: "{{ item }}"
    state: absent
  with_items: "{{remove_package}}"
  when: mysql_exist.rc == 0
- name: install dependency package
  apt: name=software-properties-common state=present update_cache=true
- name: add the GPG key
  command: apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
- name: add repositories
  apt_repository:
    repo: deb [arch=amd64,arm64,i386,ppc64el] http://ftp.kaist.ac.kr/mariadb/repo/10.3/ubuntu xenial main
    state: present
    filename: mariadb
- name: Set MySQL root password before installing
  command: debconf-set-selections <<< 'mariadb-server-10.3 mysql-server/root_password password {{mariadb_root_password}}'
- name: Confirm MySQL root password before installing
  command: debconf-set-selections <<< 'mariadb-server-10.3 mysql-server/root_password_again password {{mariadb_root_password}}'
- name: install mariadb 10.3 in ubuntu
  package:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items: "{{mariadb_packages}}"
  notify:
    - start
- name: remove .my.cnf if existing
  file:
    path: /root/.my.cnf
    state: absent
#- name: Add .my.cnf
#  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
#  notify:
#    - start
- name: serice restart
  service:
    name: mysql
    state: restarted

- name: update mysql root password for all root accounts
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mariadb_root_password }}"
      login_user: root
      login_password: "{{ mariadb_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

#  notify:
#    - start
#- name: Check if root password is set
#  shell: >
#    mysqladmin -u root status
#  changed_when: false
#  failed_when: false
#  register: root_pwd_check
#- name: copy .my.cnf file which contains root user passowrd
#  template:
#    src: .my.cnf.j2
#    dest: /root/.my.cnf
#    owner: root
#    mode: 0600
#  notify:
#    - start
#- name: Set MariaDB root password for the first time (root@localhost)
#  mysql_user:
#    name: root
#    password: "{{ mariadb_root_password }}"
#    host: localhost
#    state: present
#  when: root_pwd_check.rc == 0
#- name: Set MariaDB root password for 127.0.0.1, ::1
#  mysql_user:
#    name: root
#    password: "{{ mariadb_root_password }}"
#    host: "{{ item }}"
#    login_user: root
#
#    login_password: "{{ mariadb_root_password }}"
#    state: present
#  with_items:
#    - ::1
#    - 127.0.0.1
#  when: root_pwd_check.rc == 0
