---
# tasks file for mariadb103ubuntu
-name: install dependency package
 aptt: name=software-properties-common state=installed update_cache=true
- name: add the GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0xF1656F24C74CD1D8
- name: add repositories
  apt_repository:
    repo: deb https://mirrors.evowise.com/mariadb/repo/10.1/ubuntu {{ distro }}' main
    state: present
    filename: mariadb
- name: install mariadb 10.3 in ubuntu
  package:
    name: "{{ item }}"
    state: installed
    update_cache: true
  with_items: "{{mariadb_packages}}"
  notify:
    - start
- name: Check if root password is set
  shell: >
    mysqladmin -u root status
  changed_when: false
  failed_when: false
  register: root_pwd_check
- name: Set MariaDB root password for the first time (root@localhost)
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: localhost
    state: present
  when: root_pwd_check.rc == 0
- name: Set MariaDB root password for 127.0.0.1, ::1
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
  when: root_pwd_check.rc == 0
