---
 - name: install dependencies packages
   package:
      name: "{{depen}}"
      state: present
 - name: add the gpg key
   shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add "
 - name: add repository
   apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present
    filename: docker.list
 - name: install docker CE in ubuntun server
   apt:
     name: docker-ce
     state: present
     update_cache: yes
   notify:
   - start